using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using Scripts.StateMachine;
using System.ComponentModel;
using Scripts.Common;

namespace Scripts.Monster
{
    public class Monster : MonoBehaviour, IDamageable, IAttacker, Common.IPoolable
    {
        //2СОЗљ.3СОЗљ,...50СОЗљ
        public StateMachine<Monster> _machine { get; private set; }
        public Rigidbody2D _rb { get; private set; }
        public Animator _animator { get; private set; }
        public SpriteRenderer _spriteRenderer { get; private set; }
        // ЛѓХТ
        public IdleState StateIdle { get; private set; }
        public PatrolState StatePatrol { get; private set; }
        public ChaseState StateChase { get; private set; }
        public AttackState StateAttack { get; private set; }
        public HitState StateHit { get; private set; }
        public int attackPower => (int)_attackDamage;

        // ИѓНКХЭ НКХШ
        private int _maxHp;
        private int _currentHp;

        public float _moveSpeed;
        public float _patrolSpeed;
        public float _chaseSpeed;

        public float _detectionRange;
        public float _attackDamage;

        //Idle КЏМіМГСЄ
        public float _idleWaitTime;

        // Patrol КЏМіМГСЄ
        public float _patrolRange;
        public float _patrolDuration;
        private Vector2 _startPosition;
        public Transform _cliffCheckPos;
        public eLayerMask _groundLayer;
        public float _cliffCheckDistance;
        public float _wallCheckDistance;
        // Attack КЏМіМГСЄ
        public float _attackRange; // АјАнРЛ НУРлЧв АХИЎ 
        public float _dashSpeed;// АјАн ДыНЌ МгЕЕ
        public float _attackWaitTime = 0.5f;   // АјАн Рќ ДыБт НУАЃ 
        public float _dashDuration = 0.3f;       // НЧСІ ЕЙСјЧЯДТ НУАЃ
        public float _attackTotalTime = 1.5f;    // РќУМ АјАн И№МЧ НУАЃ
        private float _lastTouchDamageTime;
        // Hit КЏМі МГСЄ
        public float _hitRecoveryTime;
        // ЧУЗЙРЬОю РЇФЁ ЙоБт
        public Transform _target;
        public float _verticalDetectionRange;

        private void Awake()
        {
            _rb = GetComponent<Rigidbody2D>();
            _animator = GetComponent<Animator>();

            _spriteRenderer = GetComponent<SpriteRenderer>();
            // КЏМі МГСЄ
            Init();
        }

        private void Init()
        {
            _maxHp = 50;
            _attackRange = 3.5f;
            _dashSpeed = 20f;
            _patrolSpeed = 2f;
            _patrolRange = 3f;
            _chaseSpeed = 6f;
            _detectionRange = 7.5f;
            _verticalDetectionRange = 1f;
            _wallCheckDistance = 2f;
            _cliffCheckDistance = 0.3f;
            _idleWaitTime = 1.5f;
            _patrolDuration = 3.0f;
            _hitRecoveryTime = 0.5f;
            _attackDamage = 10f;
        }

        private void Start()
        {
            _machine = new StateMachine<Monster>();

            StateIdle = new IdleState(this, _machine);
            StatePatrol = new PatrolState(this, _machine);
            StateChase = new ChaseState(this, _machine);
            StateAttack = new AttackState(this, _machine);
            StateHit = new HitState(this, _machine);
            _currentHp = _maxHp;
            _startPosition = transform.position;

            _moveSpeed = _patrolSpeed;
            // ЧУЗЙРЬОю ХТБз ШАПыЧиМ­ СИРчЧЯДТСі УМХЉ       
            GameObject playerObj = GameObject.FindGameObjectWithTag("Player");
            if (playerObj != null)
            {
                _target = playerObj.transform;

            }
            _machine.BeginMachine(StateIdle);
        }

        private void Update()
        {
            if (_machine.currentState != null)
            {
                _machine.currentState.EntityUpdate();
            }

            if (Input.GetKeyDown(KeyCode.H))
            {
                Debug.Log("А­СІ ЧЧАн ХзНКЦЎ!");
                // ЕЅЙЬСі 10, АјАнРкДТ nullЗЮ РгНУ ХзНКЦЎ
                TakeDamage(10, null);
            }

        }

        public void Die()
        {
            _animator.SetBool("IsDead", true);
            // ФнЖѓРЬДѕ ВєАэ, НКХЉИГЦЎ КёШАМКШ­ЧЯБт
            GetComponent<Collider2D>().enabled = false;
            this.enabled = false;

            Destroy(gameObject, 1.5f);
        }

        // ИѓНКХЭ РЬЕПЧдМі
        public void Move(Vector2 _direction)
        {
            _rb.velocity = _direction * _moveSpeed;
            Flip(_direction.x);

        }
        // ЙцЧт РќШЏРЛ РЇЧб ЧдМі
        public void Flip(float _xDirection)
        {
            Vector3 _currentScale = transform.localScale;

            // ПРИЅТЪРИЗЮ РЬЕП
            if (_xDirection > 0.1f)
            {
                _currentScale.x = Mathf.Abs(_currentScale.x);
            }
            // ПоТЪРИЗЮ РЬЕП
            if (_xDirection < -0.1f)
            {
                _currentScale.x = -Mathf.Abs(_currentScale.x);
            }

            transform.localScale = _currentScale;
        }
        // ИѓНКХЭАЁ ИиУпБт РЇЧб ЧдМі
        public void Stop()
        {
            _rb.velocity = Vector2.zero;
        }

        public float GetToTarget()
        {

            if (_target == null) return 9999f;

            // yУр АшЛъ
            float _yDifference = Mathf.Abs(_target.position.y - transform.position.y);
            if (_yDifference > _verticalDetectionRange)
            {
                return 9999f;
            }

            //  XУр ЙцЧт АшЛъ
            // ПРИЅТЪРЬИщ (1, 0), ПоТЪРЬИщ (-1, 0)
            float _dir = Mathf.Sign(_target.position.x - transform.position.x);
            Vector2 _xDirection = new Vector2(_dir, 0);
            // ЗЙРЬОю ИЖНКХЉИІ АсЧеНУФб КЎ ЕкПЁ РжДТ ЧУЗЙРЬОюИІ АЈСі ИјЧЯАд ИИЕы
            int _layerMask = (int)(eLayerMask.Player | eLayerMask.Ground);
            // МіЦђ ЗЙРЬФГНКЦЎ ЙпЛч
            RaycastHit2D _playerHit = Physics2D.Raycast(transform.position, _xDirection, _detectionRange, _layerMask);

            // АсАњ ЦЧСЄ      
            if (_playerHit.collider != null && _playerHit.collider.CompareTag("Player"))
            {
                // НЧСІ АХИЎ ЙнШЏ (xУр АХИЎИИ ЙнШЏ)
                return Mathf.Abs(_target.position.x - transform.position.x);
            }

            // КЎПЁ ИЗЧћАХГЊ ОјРИИщ Иј КЛ УД
            return 9999f;
        }

        // ЧУЗЙРЬОюИІ ЧтЧи ЦЏСЄ МгЕЕЗЮ РЬЕПЧЯБт РЇЧи ИИЕч ЧдМі
        public void MoveToTarget(float _speed)
        {
            if (_target == null) return;
            // ЙцЧт БИЧЯБт (ПРИЅТЪРК 1, ПоТЪРК -1)
            float _dir = Mathf.Sign(_target.position.x - transform.position.x);

            _rb.velocity = new Vector2(_dir * _speed, 0);
            Flip(_dir);
        }

        // ГЖЖАЗЏСі УМХЉ
        public bool IsCliff()
        {
            RaycastHit2D _groundHit = Physics2D.Raycast(_cliffCheckPos.position, Vector2.down, _cliffCheckDistance, (int)_groundLayer);
            return _groundHit.collider == null;
        }
        // КЎ УМХЉ
        public bool IsWall(float _dir)
        {
            // ЗЙРЬРњ НУРлСЁ
            Vector2 origin = transform.position;
            // СјЧр ЙцЧт(_dir)РИЗЮ ЗЙРЬРњ ЙпЛч      
            RaycastHit2D hit = Physics2D.Raycast(origin, new Vector2(_dir, 0), _wallCheckDistance, (int)_groundLayer);


            return hit.collider != null;
        }
        private bool CanTouchAttack()
        {
            // (ЧіРч НУАЃ - ИЖСіИЗ АјАн НУАЃ)РЬ ДыБт НУАЃКИДй ХЉИщ АјАн АЁДЩ(True)
            return Time.time - _lastTouchDamageTime >= _attackWaitTime;
        }


        // УцЕЙУГИЎ ( ИѓНКХЭ АјАн, ИіЙкАјАн ) 
        private void OnCollisionEnter2D(Collision2D collision)
        {
            if (collision.gameObject.CompareTag("Player"))
            {
                if (_machine.currentState != StateAttack) return;

                if (!CanTouchAttack())
                {
                    return;
                }

                IDamageable target = collision.gameObject.GetComponent<IDamageable>();

                if (target != null)
                {

                    Attack(target);


                }

            }
        }


        public void TakeDamage(int atk, IAttacker attacker)
        {

            if (_currentHp <= 0) return;

            _currentHp -= atk;
            _animator.SetTrigger("IsHit");

            if (_currentHp > 0)
            {
                _machine.ChangeState(StateHit);
            }
            else
            {
                Die();
            }
        }


        public void Attack(IDamageable target)
        {
            if (target != null)
            {
                target.TakeDamage(this.attackPower, this);
            }

        }

        public Vector3 GetAttackerPos()
        {
            return transform.position;
        }

        public void OnAlloc()
        {
            Init();
            _rb.velocity = Vector2.zero;
            GetComponent<Collider2D>().enabled = true;
            this.enabled = true;
        }

        public void OnRelease()
        {
            //ЙАИЎСЄКИ УЪБтШ­.
            _rb.velocity = new Vector2(0, 0);
        }

       

        private void OnDrawGizmos()
        {
            // ДЋГєРЬ ЧуПы ЙќРЇ
            Gizmos.color = Color.green;
            Vector3 center = transform.position;
            Vector3 size = new Vector3(_detectionRange * 2, _verticalDetectionRange * 2, 0);
            Gizmos.DrawWireCube(center, size);

            Gizmos.color = Color.red;
            Vector3 origin = transform.position;
            Gizmos.DrawLine(origin, origin + Vector3.right * _wallCheckDistance);
            Gizmos.DrawLine(origin, origin + Vector3.left * _wallCheckDistance);

            // НЧСІ ЗЙРЬРњ БзИЎБт 
            if (_target != null)
            {
                float yDiff = Mathf.Abs(_target.position.y - transform.position.y);
                if (yDiff <= _verticalDetectionRange)
                {
                    Vector2 xDir;


                    if (_target.position.x > transform.position.x)
                    {
                        xDir = Vector2.right; // (1, 0)
                    }
                    else
                    {
                        xDir = Vector2.left;  // (-1, 0)
                    }
                    Gizmos.color = Color.red;
                    Gizmos.DrawLine(transform.position, transform.position + (Vector3)(xDir * _detectionRange));
                }
            }
            if (_cliffCheckPos != null)
            {
                Gizmos.color = Color.cyan;
                Gizmos.DrawLine(_cliffCheckPos.position, _cliffCheckPos.position + Vector3.down * _cliffCheckDistance);
            }
        }
    }
}

