using System.Collections;
using System.Collections.Generic;
using System.Threading;
using UnityEngine;
using Scripts.Common;

namespace Scripts.Boss
{
    public class FallDebris : MonoBehaviour, IAttacker
    {
        [Header("ГЋЧЯ МГСЄ")]
        public float _warningDuration = 0.3f; // ЖГОюСіБт Рќ ДыБт НУАЃ 
        public float _fallGravity = 0.5f;     // ЖГОюСњ ЖЇ СпЗТ (МгЕЕ)
        public int _damage = 10;

        private bool _canDestroyOnGround = false;

        private Rigidbody2D _rb;
        private SpriteRenderer _sprite;

        public int attackPower => _damage;
        private void Awake()
        {
            _rb = GetComponent<Rigidbody2D>();
            _sprite = GetComponent<SpriteRenderer>();

            _rb.gravityScale = 0;

        }
        private void Start()
        {

            StartCoroutine(FallProcess());
        }


        IEnumerator FallProcess()
        {
            float _timer = 0f;
            while (_timer < _warningDuration)
            {
                _timer += Time.deltaTime;

                yield return null;
            }
            _rb.gravityScale = _fallGravity;

            yield return new WaitForSeconds(0.4f);

            _canDestroyOnGround = true;
        }

        private void OnTriggerEnter2D(Collider2D _collision)
        {
            if (_collision.CompareTag("Ground"))
            {
                
                if (_canDestroyOnGround)
                {
                    DestroyDebris();
                }
            }
            else if (_collision.CompareTag("Player"))
            {
                // ЧУЗЙРЬОю ЧЧАн УГИЎ
                IDamageable target = _collision.GetComponent<IDamageable>();
                if (target != null)
                {
                    // IAttacker СЄКИИІ ГбАмСжИч ЕЅЙЬСі РдШћ
                    target.TakeDamage(attackPower, this);
                }

                DestroyDebris();
            }
        }

        private void DestroyDebris()
        {
           
            Destroy(gameObject);
        }

      
        public Vector3 GetAttackerPos()
        {
            return transform.position;
        }

        // IAttacker РЮХЭЦфРЬНК БИЧі: АјАн ЧдМі (TriggerЗЮ УГИЎЧЯЙЧЗЮ КёПіЕв)
        public void Attack(IDamageable target)
        { 
        }
    }

}


