using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace D
{
    public class SceneManager4 : MonoBehaviour
    {
        //public void MoveScene()
        //{
        //    UnityEngine.SceneManagement.SceneManager.LoadScene("sceneName");
        //}

        public void OnClickStart()
        {
            UnityEngine.SceneManagement.SceneManager.LoadScene("MainMenu");
        }

        // ОР РЬИЇРИЗЮ РЬЕП
        public void LoadSceneByName(string sceneName)
        {
            UnityEngine.SceneManagement.SceneManager.LoadScene(sceneName);
        }

        // ОР РЮЕІНКЗЮ РЬЕП
        public void LoadSceneByIndex(int index)
        {
            UnityEngine.SceneManagement.SceneManager.LoadScene(index);
        }

        // АдРг СОЗс (PC КєЕх РќПы)
        public void QuitGame()
        {
            Application.Quit();
        }

        // Start is called before the first frame update
        void Start()
        {

        }

        // Update is called once per frame
        void Update()
        {

        }
    }
}