using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class BackDashState : MonoBehaviour
{
    private SpriteRenderer _playerSpriteRenderer;
    private PlayerMove _playerMove;
    public Rigidbody2D _rb;
    public Animator _dashAnim;
    public Player _player;

    // ДыНУ АќЗУ
    private bool _canDash = true;
    private bool _isDashing;
    private bool _isRun = false;
    private float _dashingPower = 7f;
    private float _dashingTime = 0.5f;
    private float _dashingCooldown = 1f;

    private void Awake()
    {
        _playerSpriteRenderer = GetComponent<SpriteRenderer>();
        _rb = GetComponent<Rigidbody2D>();
        _playerMove = new PlayerMove();
        _dashAnim = GetComponent<Animator>();
        _player = GetComponent<Player>();
    }

    private void OnEnable()
    {
        // РдЗТ ИЪРЛ Чб ЙјИИ ШАМКШ­
        _playerMove?.Player.Enable();
    }

    private void OnDisable()
    {
        // КёШАМКШ­
        _playerMove?.Player.Disable();
    }

    private IEnumerator DashAndBackDash()
    {
        Vector2 dir = _player.transform.position;

        // canDash(Ф№ХИРг АшЛъПы), isDash(ЕПРл ЛѓХТ АќИЎПы)РЛ УЪБтШ­
        _canDash = false;
        _isDashing = true;

        // ДыНЌСпПЁДТ YУрРЬ КЏЧЯСі ОЪАд ЧЯБт РЇЧи СпЗТРЛ СІАХЧбДй.
        float originalGfavity = _rb.gravityScale;

        // Бз РќПЁ ПјЗЁРЧ СпЗТ(GravityScale) АЊРЛ КЏМіПЁ РњРхЧбДй.
        _rb.gravityScale = 0f;

        // АЁИИШї М­РжРЛ ЖЇРЧ ДыНЌ ЙцЧтРЛ СЄЧиСм
        if (dir.x == 0) dir = Vector2.right;

        // МгЗТРЛ МіСЄ, БзИЎАэ dashingTime ШФПЁ СОЗс
        // VectorАЊРЛ СрМ­ ЧУЗЙРЬОюРЧ РЇФЁАЊРЛ ШћРЧ АЊРИЗЮ ЙоОЦЙіИВ > ЧУЗЙРЬОю РЇФЁРЧ Р§ДыАЊРЬ ХЌ МіЗЯ ШћРЬ ММСќ
        if (!_isRun) // ДоИЎБт or АШБт ЛѓХТАЁ ОЦДв ЖЇ
        {
            if (_playerSpriteRenderer.flipX == false) // ПРИЅТЪ ЙйЖѓКМ ЖЇ
            {
                if (_playerMove.Player.Dash.IsPressed())
                {
                    _rb.velocity = new Vector2(_dashingPower, 0f); // ПРИЅТЪ ЙщДыНУ
                }
            }
            else // ПоТЪ ЙйЖѓКМ ЖЇ
            {
                if (_playerMove.Player.Dash.IsPressed())
                {
                    _rb.velocity = new Vector2(-_dashingPower, 0f); // ПоТЪ ЙщДыНУ
                }
            }
        }
        else // ДоИЎБт or АШБт ЛѓХТРЯ ЖЇ
        {

            if (_playerSpriteRenderer.flipX == false) // ПРИЅТЪ ЙйЖѓКМ ЖЇ
            {
                if (_playerMove.Player.Dash.IsPressed())
                {
                    _rb.AddForce(new Vector2(_dashingPower * 10, 0f), ForceMode2D.Impulse); // ПРИЅТЪ ЙщДыНУ
                }
            }
            else // ПоТЪ ЙйЖѓКМ ЖЇ
            {
                if (_playerMove.Player.Dash.IsPressed())
                {
                    _rb.AddForce(new Vector2(-_dashingPower * 10, 0f), ForceMode2D.Impulse); // ПоТЪ ЙщДыНУ
                }
            }
        }

        _dashAnim.SetBool("isDash", true); // ДыНУ ОжДЯИХРЬМЧ НЧЧр
        yield return new WaitForSeconds(_dashingTime);

        // playerРЧ СпЗТРЛ ЕЙЗС ГѕАэ isDashingРЛ false
        _rb.gravityScale = originalGfavity;
        _isDashing = false;

        // Дм, Ф№ХИРг АшЛъРЛ РЇЧи canDashДТ new WaitForSeconds(dashingCooldown); ИІ ХыЧи dashingCooldown ШФПЁ trueЗЮ УЪБтШ­
        yield return new WaitForSeconds(_dashingCooldown);
        _canDash = true;

        // ДыНУ ОжДЯИоРЬМЧ СОЗс
        _dashAnim.SetBool("isDash", false);
    }

    void OnDash()
    {
        if ((_playerMove.Player.Dash.IsPressed() || _playerMove.Player.BackDash.IsPressed()) && _canDash)
        {
            StartCoroutine(DashAndBackDash());
        }
    }

    void Upddate()
    {
        OnDash();
    }

    /**
   virtual void OnEnter()
   {

   }

   virtual void OnUpdate()
   {

   }

   virtual void OnExit()
   {

   }
   **/

}
