using Scripts.Player;
using Scripts.Player.Bullets;
using Unity.VisualScripting;
using UnityEngine;

[RequireComponent(typeof(Collider2D))]
public class FloorTriggerSimple : MonoBehaviour
{
    // InspectorПЁ РЬЕПНУХГ TransformРЛ ЕхЗЁБзЧЯММПф.
    public Transform Floor1;
    public Transform Floor2_Start;
    public Transform Floor2;
    public Transform Floor3_Start;
    public Transform Floor3;
    // public Transform Boss;
    public Transform Player;

    // ИИОр FloorControllerИІ ХыЧи АќИЎЧЯАэ НЭРИИщ ЧвДчЧиЕЕ ЕЫДЯДй(МБХУ)
    public FloorController floorController;

    [Tooltip("УбОЫ РЇФЁПЭ ЧУЗЮОю РЇФЁ КёБГ НУ ЧуПыЕЧДТ xУр АХИЎ")]
    public float positionTolerance = 1f;

    void Reset()
    {
        // Collider2DАЁ TriggerЗЮ МГСЄЕЧОю РжДТСі ШЎРЮ
        var col = GetComponent<Collider2D>();
        Debug.Log(col);
        // TriggerЗЮ МГСЄ
        if (col != null) col.isTrigger = true;
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        //by junGi
        Bullet bullet = other.GetComponent<Bullet>();
        //BulletРЬ ОЦДбАцПь
        if (bullet == null)
        {
            Debug.Log("Is Not Bullet!");
            return;
        }


        float bulletY = bullet.transform.position.y;
        if (bullet.IsHackingBullet)
        {
            //РЬЕПЧЯИщ ЕЫДЯДй.
            if (Mathf.Abs(bulletY - Floor1.position.y) <= positionTolerance)
            {
                floorController.TeleportPlayer(Floor2_Start);
            }
            else if (Mathf.Abs(bulletY - Floor2.position.y) <= positionTolerance)
            {
                floorController.TeleportPlayer(Floor3_Start);
            }
            else if (Mathf.Abs(bulletY - Floor3.position.y) <= positionTolerance)
            {
                floorController.TeleportToBoss();
            }
            else
            {
                Debug.Log("КјИТУу");
            }
        }

        // teleportTargetРЬ МГСЄЕЧОю РжДТСі ШЎРЮ
        if (Floor1 == null && Floor2 == null && Floor3 == null && Floor2_Start == null && Floor3_Start == null)
        {
            Debug.LogWarning("teleportTargetРЬ МГСЄЕЧСі ОЪРНПф");
            return;
        }
        // FloorControllerАЁ ЧвДчЕЧОю РжРИИщ БзТЪРЛ ХыЧи РЬЕП
        /*if (floorController != null)
        {
            // FloorControllerАЁ РжРИИщ БзТЪ ИоМ­Ех ХыЧи РЬЕП
            floorController.TeleportPlayer(teleportTarget);
        }
        // FloorControllerАЁ ОјРИИщ СїСЂ РЬЕП
        {
            // ЧУЗЙРЬОюРЧ Rigidbody2D ФФЦїГЭЦЎ АЁСЎПРБт
            var rb = other.GetComponent<Rigidbody2D>();
            // Rigidbody2DАЁ РжДйИщ МгЕЕИІ 0РИЗЮ УЪБтШ­ЧиМ­ МјАЃРЬЕП УцЕЙ ЙЎСІ ЙцСі
            if (rb != null) rb.velocity = Vector2.zero;
            // ЧУЗЙРЬОю РЇФЁИІ teleportTarget РЇФЁЗЮ МГСЄ
            other.transform.position = teleportTarget.position;
            Debug.Log($"[FloorTriggerSimple] Bullet teleported to {teleportTarget.name} by {name}");
        }*/
    }
}